// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ooqufmiiwriwdezgaqby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vcXVmbWlpd3Jpd2RlemdhcWJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MjcwMTcsImV4cCI6MjA1NzMwMzAxN30.fUkleh448PGPQSTeXjw35yQmyMLxWz9571YICVdjvXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);